# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: v1
kind: Service
metadata:
  name: {{ include "medworkup.fullname" . }}-embedding
  labels:
    {{- include "medworkup.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.embedding }}
      targetPort: {{ .Values.ports.embedding }}
  selector:
    app: {{ include "medworkup.fullname" . }}-embedding
