# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: v1
kind: Service
metadata:
  name: {{ include "fintech.complexName" . }}-xgb
  labels:
    {{- include "fintech.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.xgb }}
      targetPort: {{ .Values.ports.xgb }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "fintech.complexName" . }}-xgb
